name: Deploy to Railway

on: [push, pull_request]

jobs:

  package:
    name: Maven Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
  test:
    name: Maven Tests
    needs: package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Maven Verify
        run: mvn -B clean verify
  deploy:
    name: Railway Deploy
    needs: test
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Authenticate with Railway
        run: railway login --api ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Deploy to Service A
        run: railway up -s healthtrackerrest
